# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Easy
version:      1.01
version_from: Easy.pm
installdirs:  site
requires:
    Exporter:                      5.562
    strict:                        0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
