---
abstract: 'facilitates easy testing patterns'
author:
  - 'Belden Lyman <belden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Easy
no_index:
  directory:
    - t
    - inc
requires:
  Data::Denter: 0
  Data::Difflet: 0.06
  Functional::Utility: 1.02
  Hash::MostUtils: 1.05
  Scalar::Util: 0
  Test::More: 0
  Test::Resub: 0
resources:
  bugtracker: https://github.com/belden/perl-test-easy/issues
  homepage: https://github.com/belden/perl-test-easy
  repository: git://github.com/belden/perl-test-easy.git
version: 1.08
